# Generated by Django 5.0.1 on 2024-01-23 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=300)),
                ('Author_Name', models.CharField(max_length=300)),
                ('File_Data', models.FileField(upload_to='')),
                ('Status', models.CharField(max_length=300)),
                ('Create_Date', models.DateField(default=django.utils.timezone.now)),
                ('Update_Date', models.DateField(null=True)),
            ],
        ),
    ]
